## cachematrix will save costly computing time by caching the inverse of a matrix.
## These functions will cache a matrix and then cache its inverse
## 
## Usage:
##  Call makeCacheMatrix() by passing a matrix
##  Example: M <- matrix(c(1,2,3,4), nrows=2, ncol=2)
##           myMatrix <- makeCacheMatrix(M)
##  Create the inverse of the matrix
##  Example: cacheSolve(myMatrix)
##
##  Change the matrix being cached.
##       cacheMatrix$set(M)
##  Return the matrix being cached.
##       cacheMatrix$get()
##  After running cacheSolve() you can return the inverse of the matrix
##       cacheMatrix$getInverse()


## The function makeCacheMatrix creates a special matix object that can cache its inverse
## The result will be a list of four functions that can be called
## 1. set to create a cache of received matrix
## 2. get to return the matrix from the cache
## 3. setInverse to create a cache of the inversed matrix
## 4. getInverse to return the cached matrix
##
##  m is the matrix set up to cache new matrix and the inversed matrix. It is also saved globally
##  y is a local variable that receives a new matrix when set is called
##  x is a global varaiable that holds the matrix to return in get

makeCacheMatrix <- function(x = matrix()) {

      m <- NULL
      
      set <- function(y) {
          
             x <<- y
             
             m <<- NULL
      }

      get <- function () x

      setInverse <- function(matrixIn) m <<- matrixIn

      getInverse <- function() m

      list(set=set, get=get, setInverse=setInverse, getInverse=getInverse)

}


## The function cacheSolve computes the inverse of a cached matrix.
## If the inverse has already been calculated, the funtion will retrieve the inverse from the cache
## The function receives as an argument a list of functions created by makeCacheMatrix
##
## x passes the list generated by makeCacheMatrix.
##   x<-MakeCacheMatrix(myMatrix)
## m is a local variable to receive the matrix
## if m is not null, it is returned. It already holds the inverse
## if m is null, it used to receive the inverse of the matrix and returned.

cacheSolve <- function(x, ...) {
       
      m <- x$getInverse()

      if(!is.null(m)){
           
           print ("getting cached data")

           return(m)
     
      }

      data <- x$get()

      m <- solve(data, ...)

      x$setInverse(m)

      m


}
